name: BuildOsxArm

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string

jobs:
  build-osx-arm:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Create binary
        run: |
          VERSION=${{ inputs.project-version }}
          dotnet build --configuration Release
          mkdir bin
          dotnet publish src/helloworld/helloworld.csproj -r osx-arm64 --configuration Release /p:Version=$VERSION --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --output bin/osx-arm64

      - name: Sign binary
        run: |
          codesign -f -s - bin/osx-arm64/helloworld

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: binaries-osx-arm
          path: |
            bin/osx-arm64/helloworld
